version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"